version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      # Змінні середовища для підключення до БД
      - SQLALCHEMY_DATABASE_URL=postgresql+psycopg2://postgres:567234@postgres-db:5432/hw02
    depends_on:
      - postgres-db
    restart: on-failure

  postgres-db:
    image: postgres:14
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=567234
      - POSTGRES_DB=hw02
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure

volumes:
  postgres_data: